/**
 * Marcas e modelos mais populares no Brasil lançados a partir de 2016.
 * Cada modelo é um item individual separado para uso direto em elementos <select>.
 */

export const MARCAS_POPULARES_POR_TIPO: Record<string, string[]> = {
  Celular: [
    "Samsung",
    "Motorola",
    "Apple",
    "Xiaomi",
    "LG",
    "Realme",
    "Asus",
    "Infinix",
    "Huawei",
    "Positivo",
    "Multilaser",
    "Outra",
  ],
  Tablet: ["Apple", "Samsung", "Lenovo", "Xiaomi", "Multilaser", "Positivo", "Amazon", "Outra"],
  Notebook: [
    "Dell",
    "Lenovo",
    "Acer",
    "Samsung",
    "ASUS",
    "Apple",
    "HP",
    "Positivo",
    "VAIO",
    "Avell",
    "Outra",
  ],
  Computador: ["Dell", "Lenovo", "HP", "Apple", "Positivo", "PC Gamer / Customizado", "Outro"],
  Outro: [
    "Samsung",
    "Apple",
    "Xiaomi",
    "Sony (PlayStation)",
    "Microsoft (Xbox)",
    "Nintendo",
    "JBL",
    "Outra",
  ],
};

export const MODELOS_INDIVIDUAIS_POR_MARCA: Record<string, string[]> = {
  // ==========================================
  // SAMSUNG (Cada modelo é um item individual)
  // ==========================================
  Samsung: [
    // Linha Galaxy A (2019 - 2024+)
    "Galaxy A01",
    "Galaxy A01 Core",
    "Galaxy A02",
    "Galaxy A02s",
    "Galaxy A03",
    "Galaxy A03 Core",
    "Galaxy A03s",
    "Galaxy A04",
    "Galaxy A04e",
    "Galaxy A04s",
    "Galaxy A05",
    "Galaxy A05s",
    "Galaxy A06",
    "Galaxy A10",
    "Galaxy A10s",
    "Galaxy A11",
    "Galaxy A12",
    "Galaxy A13 4G",
    "Galaxy A13 5G",
    "Galaxy A14 4G",
    "Galaxy A14 5G",
    "Galaxy A15 4G",
    "Galaxy A15 5G",
    "Galaxy A16 5G",
    "Galaxy A20",
    "Galaxy A20s",
    "Galaxy A21s",
    "Galaxy A22 4G",
    "Galaxy A22 5G",
    "Galaxy A23 4G",
    "Galaxy A23 5G",
    "Galaxy A24",
    "Galaxy A25 5G",
    "Galaxy A30",
    "Galaxy A30s",
    "Galaxy A31",
    "Galaxy A32 4G",
    "Galaxy A32 5G",
    "Galaxy A33 5G",
    "Galaxy A34 5G",
    "Galaxy A35 5G",
    "Galaxy A50",
    "Galaxy A51",
    "Galaxy A52 4G",
    "Galaxy A52 5G",
    "Galaxy A52s 5G",
    "Galaxy A53 5G",
    "Galaxy A54 5G",
    "Galaxy A55 5G",
    "Galaxy A70",
    "Galaxy A71",
    "Galaxy A72",
    "Galaxy A73 5G",
    "Galaxy A80",

    // Linha Galaxy S (2016 a 2024+)
    "Galaxy S7",
    "Galaxy S7 Edge",
    "Galaxy S8",
    "Galaxy S8+",
    "Galaxy S9",
    "Galaxy S9+",
    "Galaxy S10e",
    "Galaxy S10",
    "Galaxy S10+",
    "Galaxy S10 Lite",
    "Galaxy S20",
    "Galaxy S20+",
    "Galaxy S20 Ultra",
    "Galaxy S20 FE",
    "Galaxy S21",
    "Galaxy S21+",
    "Galaxy S21 Ultra",
    "Galaxy S21 FE",
    "Galaxy S22",
    "Galaxy S22+",
    "Galaxy S22 Ultra",
    "Galaxy S23",
    "Galaxy S23+",
    "Galaxy S23 Ultra",
    "Galaxy S23 FE",
    "Galaxy S24",
    "Galaxy S24+",
    "Galaxy S24 Ultra",
    "Galaxy S24 FE",

    // Linha Galaxy M (Bateria Grande)
    "Galaxy M10",
    "Galaxy M12",
    "Galaxy M13",
    "Galaxy M14 5G",
    "Galaxy M15 5G",
    "Galaxy M20",
    "Galaxy M21s",
    "Galaxy M22",
    "Galaxy M23 5G",
    "Galaxy M30",
    "Galaxy M31",
    "Galaxy M32",
    "Galaxy M34 5G",
    "Galaxy M35 5G",
    "Galaxy M51",
    "Galaxy M52 5G",
    "Galaxy M53 5G",
    "Galaxy M54 5G",
    "Galaxy M55 5G",
    "Galaxy M62",

    // Linha Galaxy J (2016 a 2018)
    "Galaxy J2 Prime",
    "Galaxy J2 Pro",
    "Galaxy J4",
    "Galaxy J4+",
    "Galaxy J4 Core",
    "Galaxy J5 (2016) Metal",
    "Galaxy J5 Prime",
    "Galaxy J5 Pro",
    "Galaxy J6",
    "Galaxy J6+",
    "Galaxy J7 (2016) Metal",
    "Galaxy J7 Prime",
    "Galaxy J7 Prime 2",
    "Galaxy J7 Pro",
    "Galaxy J8",

    // Linha Galaxy Note e Dobráveis
    "Galaxy Note 8",
    "Galaxy Note 9",
    "Galaxy Note 10",
    "Galaxy Note 10+",
    "Galaxy Note 10 Lite",
    "Galaxy Note 20",
    "Galaxy Note 20 Ultra",
    "Galaxy Z Flip",
    "Galaxy Z Flip 3 5G",
    "Galaxy Z Flip 4 5G",
    "Galaxy Z Flip 5 5G",
    "Galaxy Z Flip 6 5G",
    "Galaxy Z Fold 2 5G",
    "Galaxy Z Fold 3 5G",
    "Galaxy Z Fold 4 5G",
    "Galaxy Z Fold 5 5G",
    "Galaxy Z Fold 6 5G",

    // Tablets Samsung
    "Galaxy Tab A 8.0",
    "Galaxy Tab A7",
    "Galaxy Tab A7 Lite",
    "Galaxy Tab A8",
    "Galaxy Tab A9",
    "Galaxy Tab A9+",
    "Galaxy Tab S6 Lite",
    "Galaxy Tab S7",
    "Galaxy Tab S7 FE",
    "Galaxy Tab S8",
    "Galaxy Tab S9 FE",

    // Notebooks Samsung
    "Galaxy Book Go",
    "Galaxy Book 2",
    "Galaxy Book 3",
    "Galaxy Book 3 360",
    "Galaxy Book 4",
    "Samsung Book E20",
    "Samsung Book E30",
    "Samsung Book X20",
    "Samsung Book X40",
    "Samsung Flash F30",
    "Samsung Essentials E20",
    "Samsung Expert X22",
  ],

  // ==========================================
  // MOTOROLA (Cada modelo é um item individual)
  // ==========================================
  Motorola: [
    // Linha Moto G Recente (2021 a 2024+)
    "Moto G04",
    "Moto G04s",
    "Moto G13",
    "Moto G14",
    "Moto G20",
    "Moto G22",
    "Moto G23",
    "Moto G24",
    "Moto G24 Power",
    "Moto G30",
    "Moto G31",
    "Moto G32",
    "Moto G34 5G",
    "Moto G41",
    "Moto G42",
    "Moto G50 5G",
    "Moto G51 5G",
    "Moto G52",
    "Moto G53 5G",
    "Moto G54 5G",
    "Moto G60",
    "Moto G60s",
    "Moto G71 5G",
    "Moto G73 5G",
    "Moto G82 5G",
    "Moto G84 5G",
    "Moto G100 5G",
    "Moto G200 5G",

    // Linha Moto G Anteriores (2016 a 2020)
    "Moto G4",
    "Moto G4 Play",
    "Moto G4 Plus",
    "Moto G5",
    "Moto G5 Plus",
    "Moto G5S",
    "Moto G5S Plus",
    "Moto G6",
    "Moto G6 Play",
    "Moto G6 Plus",
    "Moto G7",
    "Moto G7 Play",
    "Moto G7 Power",
    "Moto G7 Plus",
    "Moto G8",
    "Moto G8 Play",
    "Moto G8 Power",
    "Moto G8 Power Lite",
    "Moto G8 Plus",
    "Moto G9 Play",
    "Moto G9 Plus",
    "Moto G9 Power",

    // Linha Moto E
    "Moto E4",
    "Moto E4 Plus",
    "Moto E5",
    "Moto E5 Play",
    "Moto E5 Plus",
    "Moto E6s",
    "Moto E6 Plus",
    "Moto E6i",
    "Moto E7",
    "Moto E7 Plus",
    "Moto E7 Power",
    "Moto E13",
    "Moto E20",
    "Moto E22",
    "Moto E22i",
    "Moto E32",
    "Moto E40",

    // Linha Edge e Razr
    "Edge 20",
    "Edge 20 Lite",
    "Edge 20 Pro",
    "Edge 30",
    "Edge 30 Neo",
    "Edge 30 Fusion",
    "Edge 30 Ultra",
    "Edge 40",
    "Edge 40 Neo",
    "Edge 50 Fusion",
    "Edge 50 Pro",
    "Edge 50 Ultra",
    "Razr 40",
    "Razr 40 Ultra",
    "Razr 50 Ultra",

    // Linha One e Moto Z
    "Motorola One",
    "Motorola One Vision",
    "Motorola One Action",
    "Motorola One Zoom",
    "Motorola One Macro",
    "Motorola One Hyper",
    "Motorola One Fusion",
    "Motorola One Fusion+",
    "Moto Z Play",
    "Moto Z2 Play",
    "Moto Z3 Play",
    "Moto X4",
  ],

  // ==========================================
  // APPLE (Cada modelo é um item individual)
  // ==========================================
  Apple: [
    // iPhones (2016 a 2024+)
    "iPhone 7",
    "iPhone 7 Plus",
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone SE (2ª Geração 2020)",
    "iPhone 12",
    "iPhone 12 Mini",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13",
    "iPhone 13 Mini",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone SE (3ª Geração 2022)",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",

    // iPads
    "iPad 5ª Geração (2017)",
    "iPad 6ª Geração (2018)",
    "iPad 7ª Geração (2019)",
    "iPad 8ª Geração (2020)",
    "iPad 9ª Geração (2021)",
    "iPad 10ª Geração (2022)",
    "iPad Air 3 (2019)",
    "iPad Air 4 (2020)",
    "iPad Air 5 (M1 2022)",
    "iPad Mini 5 (2019)",
    "iPad Mini 6 (2021)",
    "iPad Pro 11 M1 / M2",
    "iPad Pro 12.9 M1 / M2",

    // MacBooks e Computadores
    "MacBook Air 13 (2017 Intel)",
    "MacBook Air Retina (2018-2019)",
    "MacBook Air M1 (2020)",
    "MacBook Air M2 (2022)",
    "MacBook Air M3 (2024)",
    "MacBook Pro 13 (2016-2020 Intel)",
    "MacBook Pro 13 M1 (2020)",
    "MacBook Pro 13 M2 (2022)",
    "MacBook Pro 14 M1 Pro / Max",
    "MacBook Pro 14 M2 Pro / Max",
    "MacBook Pro 14 M3 / M3 Pro",
    "MacBook Pro 16 M1 / M2 / M3",
    "iMac 21.5 / 27 (Intel)",
    "iMac 24 M1 / M3",
    "Mac Mini M1 / M2",
  ],

  // ==========================================
  // XIAOMI (Cada modelo é um item individual)
  // ==========================================
  Xiaomi: [
    // Linha Redmi Note (Os mais reparados)
    "Redmi Note 7",
    "Redmi Note 7 Pro",
    "Redmi Note 8",
    "Redmi Note 8T",
    "Redmi Note 8 Pro",
    "Redmi Note 8 (Edição 2021)",
    "Redmi Note 9",
    "Redmi Note 9S",
    "Redmi Note 9 Pro",
    "Redmi Note 9T 5G",
    "Redmi Note 10",
    "Redmi Note 10S",
    "Redmi Note 10 5G",
    "Redmi Note 10 Pro",
    "Redmi Note 11",
    "Redmi Note 11S",
    "Redmi Note 11 Pro 4G",
    "Redmi Note 11 Pro 5G",
    "Redmi Note 12 4G",
    "Redmi Note 12 5G",
    "Redmi Note 12S",
    "Redmi Note 12 Pro 4G",
    "Redmi Note 12 Pro 5G",
    "Redmi Note 12 Pro+ 5G",
    "Redmi Note 13 4G",
    "Redmi Note 13 5G",
    "Redmi Note 13 Pro 4G",
    "Redmi Note 13 Pro 5G",
    "Redmi Note 13 Pro+ 5G",

    // Linha Redmi Numérica
    "Redmi 6A",
    "Redmi 7",
    "Redmi 7A",
    "Redmi 8",
    "Redmi 8A",
    "Redmi 9",
    "Redmi 9A",
    "Redmi 9C",
    "Redmi 9T",
    "Redmi 10",
    "Redmi 10A",
    "Redmi 10C",
    "Redmi 12",
    "Redmi 12C",
    "Redmi 13",
    "Redmi 13C",

    // Linha POCO
    "POCO F1",
    "POCO F3",
    "POCO F4",
    "POCO F5",
    "POCO F5 Pro",
    "POCO F6",
    "POCO F6 Pro",
    "POCO M3",
    "POCO M3 Pro 5G",
    "POCO M4 Pro 4G",
    "POCO M4 Pro 5G",
    "POCO M5",
    "POCO M5s",
    "POCO M6 Pro",
    "POCO X3 NFC",
    "POCO X3 Pro",
    "POCO X3 GT",
    "POCO X4 Pro 5G",
    "POCO X5 5G",
    "POCO X5 Pro 5G",
    "POCO X6 5G",
    "POCO X6 Pro 5G",

    // Linha Mi e Xiaomi Flagship
    "Mi A2",
    "Mi A2 Lite",
    "Mi A3",
    "Mi 8",
    "Mi 8 Lite",
    "Mi 9",
    "Mi 9 SE",
    "Mi 9T",
    "Mi 9T Pro",
    "Mi 10",
    "Mi 10T",
    "Mi 10T Pro",
    "Mi 11",
    "Mi 11 Lite 4G",
    "Mi 11 Lite 5G NE",
    "Xiaomi 12",
    "Xiaomi 12 Lite",
    "Xiaomi 13",
    "Xiaomi 13 Lite",
    "Xiaomi 13T",
    "Xiaomi 14",
    "Xiaomi 14T",

    // Tablets Xiaomi
    "Xiaomi Pad 5",
    "Xiaomi Pad 6",
    "Redmi Pad",
    "Redmi Pad SE",
  ],

  // ==========================================
  // LG
  // ==========================================
  LG: [
    "K10 (2016)",
    "K10 Novo (2017)",
    "K10 Pro",
    "K10 Power",
    "K11",
    "K11+",
    "K12+",
    "K12 Prime",
    "K12 Max",
    "K22",
    "K22+",
    "K40S",
    "K41S",
    "K50S",
    "K51S",
    "K52",
    "K61",
    "K62",
    "K62+",
    "K71",
    "LG Velvet",
    "LG G6",
    "LG G7 ThinQ",
    "LG G8X ThinQ",
    "LG Q6",
    "LG Q7+",
  ],

  // ==========================================
  // REALME
  // ==========================================
  Realme: [
    "Realme C11",
    "Realme C21Y",
    "Realme C35",
    "Realme C53",
    "Realme C55",
    "Realme C67",
    "Realme 7",
    "Realme 7 Pro",
    "Realme 7 5G",
    "Realme 8 5G",
    "Realme 8 Pro",
    "Realme 9",
    "Realme 9 Pro+",
    "Realme 10",
    "Realme 11 5G",
    "Realme 11 Pro+ 5G",
    "Realme 12 5G",
    "Realme 12 Pro+ 5G",
    "Realme GT Master Edition",
  ],

  // ==========================================
  // ASUS
  // ==========================================
  Asus: [
    "Zenfone 3",
    "Zenfone 3 Max",
    "Zenfone 3 Zoom",
    "Zenfone 4",
    "Zenfone 4 Selfie",
    "Zenfone 4 Max",
    "Zenfone 5",
    "Zenfone 5Z",
    "Zenfone 5 Selfie",
    "Zenfone 6",
    "Zenfone 7",
    "Zenfone 8",
    "Zenfone 9",
    "Zenfone 10",
    "ROG Phone 3",
    "ROG Phone 5",
    "ROG Phone 6",
    "ROG Phone 7",
    "ROG Phone 8",
    "Vivobook 15 (X515 / X1502)",
    "Vivobook 16",
    "Vivobook Go 15",
    "Zenbook 14",
    "TUF Gaming F15",
    "ROG Strix G15",
  ],

  // ==========================================
  // DELL
  // ==========================================
  Dell: [
    "Inspiron 15 3501",
    "Inspiron 15 3511",
    "Inspiron 15 3520",
    "Inspiron 15 3525",
    "Inspiron 15 5502",
    "Inspiron 15 5510",
    "Inspiron 14 3400",
    "Inspiron 14 5402",
    "Inspiron 14 5410",
    "Inspiron 14 5420",
    "Vostro 14 3400",
    "Vostro 14 3468",
    "Vostro 14 3480",
    "Vostro 15 3500",
    "Vostro 15 3510",
    "Vostro 15 3520",
    "Latitude 3400",
    "Latitude 3410",
    "Latitude 3420",
    "Latitude 5420",
    "Dell G3 3590 (Gamer)",
    "Dell G3 3500 (Gamer)",
    "Dell G5 5590 (Gamer)",
    "Dell G15 5510 (Gamer)",
    "Dell G15 5515 (Gamer)",
    "Dell G15 5520 (Gamer)",
    "Dell G15 5530 (Gamer)",
    "XPS 13",
    "XPS 15",
    "OptiPlex 3050 / 3070 / 3080",
  ],

  // ==========================================
  // LENOVO
  // ==========================================
  Lenovo: [
    "IdeaPad 1",
    "IdeaPad 1i",
    "IdeaPad 3 (15ALC6)",
    "IdeaPad 3i (15ITL6)",
    "IdeaPad 3i (15IAU7)",
    "IdeaPad S145",
    "IdeaPad 320",
    "IdeaPad 330",
    "IdeaPad 330S",
    "IdeaPad Gaming 3",
    "IdeaPad Gaming 3i",
    "Legion 5",
    "Legion 5i",
    "ThinkPad E14",
    "ThinkPad E15",
    "ThinkPad T14",
    "ThinkPad T480",
    "ThinkPad T490",
    "Yoga 7i",
    "Yoga 9i",
    "Lenovo Tab M8",
    "Lenovo Tab M9",
    "Lenovo Tab M10",
    "Lenovo Tab M10 Plus",
    "Lenovo Tab P11",
    "Lenovo Tab P11 Plus",
    "Lenovo Tab P11 Pro",
  ],

  // ==========================================
  // ACER
  // ==========================================
  Acer: [
    "Aspire 3 (A315-23)",
    "Aspire 3 (A315-34)",
    "Aspire 3 (A315-56)",
    "Aspire 3 (A315-58)",
    "Aspire 5 (A515-45)",
    "Aspire 5 (A515-54)",
    "Aspire 5 (A515-56)",
    "Aspire 5 (A515-57)",
    "Nitro 5 (AN515-54)",
    "Nitro 5 (AN515-55)",
    "Nitro 5 (AN515-57)",
    "Nitro 5 (AN515-58)",
    "Nitro V15 (ANV15-51)",
    "Predator Helios 300",
    "Predator Helios Neo 16",
    "Swift 3",
    "Spin 3",
  ],

  // ==========================================
  // HP
  // ==========================================
  HP: [
    "HP 250 G7",
    "HP 250 G8",
    "HP 250 G9",
    "HP 256 G8",
    "HP 256 G9",
    "HP Pavilion 14",
    "HP Pavilion 15",
    "HP Victus 15 (Gamer)",
    "HP Victus 16",
    "HP ProBook 440 G7 / G8",
    "HP ProBook 450 G7 / G8",
    "HP EliteBook 840 G5 / G6 / G7 / G8",
  ],

  // ==========================================
  // INFINIX
  // ==========================================
  Infinix: [
    "Infinix Hot 11",
    "Infinix Hot 11S",
    "Infinix Hot 20i",
    "Infinix Hot 20 5G",
    "Infinix Hot 30i",
    "Infinix Hot 30",
    "Infinix Note 12",
    "Infinix Note 12 Pro",
    "Infinix Note 30 5G",
    "Infinix Note 30 Pro",
    "Infinix Smart 7",
    "Infinix Smart 8",
  ],

  // ==========================================
  // POSITIVO & VAIO
  // ==========================================
  Positivo: [
    "Positivo Motion Gray Q232A",
    "Positivo Motion Gray Q464C",
    "Positivo Vision C14",
    "Positivo Vision C15",
    "Positivo Master N1240",
    "Positivo Master N1250",
    "Positivo Twist 4",
    "Positivo Twist 5",
    "Positivo Tab Q10",
  ],

  VAIO: [
    "VAIO FE14 (VJFE41F)",
    "VAIO FE14 (VJFE42F)",
    "VAIO FE14 (VJFE43F)",
    "VAIO FE15 (VJFE51F)",
    "VAIO FE15 (VJFE52F)",
    "VAIO FE15 (VJFE53F)",
    "VAIO Fit 15S",
  ],

  // ==========================================
  // MULTILASER
  // ==========================================
  Multilaser: [
    "Multilaser G Max 2",
    "Multilaser G Pro 2",
    "Multilaser F Pro 4G",
    "Multilaser M7 3G (Tablet)",
    "Multilaser M7s Plus (Tablet)",
    "Multilaser M10A (Tablet)",
    "Multilaser M10 Lite (Tablet)",
    "Multilaser Ultra UB220 (Notebook)",
    "Multilaser Ultra UB230 (Notebook)",
  ],
};

// Modelos com maior circulação e volume em bancada de assistência no Brasil pós-2016
export const MAIS_BUSCADOS_ASSISTENCIA: Array<{ tipo: string; marca: string; modelo: string }> = [
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A14 4G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A14 5G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A54 5G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A15 4G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A15 5G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A55 5G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A10" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A10s" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A12" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy A32 4G" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy S20 FE" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy J5 Prime" },
  { tipo: "Celular", marca: "Samsung", modelo: "Galaxy J7 Prime" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 11" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 13" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 14" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 12" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone XR" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 7" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 8" },
  { tipo: "Celular", marca: "Apple", modelo: "iPhone 15" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G54 5G" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G84 5G" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G24" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G60" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G7 Power" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto G8 Power" },
  { tipo: "Celular", marca: "Motorola", modelo: "Moto E22" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "Redmi Note 13 4G" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "Redmi Note 12 4G" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "Redmi Note 8" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "Redmi Note 9" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "POCO X3 Pro" },
  { tipo: "Celular", marca: "Xiaomi", modelo: "POCO X6 Pro 5G" },
  { tipo: "Celular", marca: "LG", modelo: "K10 (2016)" },
  { tipo: "Celular", marca: "LG", modelo: "K41S" },
  { tipo: "Notebook", marca: "Dell", modelo: "Inspiron 15 3520" },
  { tipo: "Notebook", marca: "Lenovo", modelo: "IdeaPad 3 (15ALC6)" },
  { tipo: "Notebook", marca: "Acer", modelo: "Aspire 5 (A515-54)" },
  { tipo: "Notebook", marca: "Acer", modelo: "Nitro 5 (AN515-54)" },
  { tipo: "Notebook", marca: "Samsung", modelo: "Samsung Book E30" },
  { tipo: "Notebook", marca: "Apple", modelo: "MacBook Air M1 (2020)" },
];

/**
 * Retorna os modelos individuais da marca informada.
 */
export function getModelosIndividuais(marca?: string): string[] {
  if (!marca) return [];

  const marcaNormalizada = marca.trim().toLowerCase();
  for (const [chave, modelos] of Object.entries(MODELOS_INDIVIDUAIS_POR_MARCA)) {
    if (chave.toLowerCase() === marcaNormalizada) {
      return modelos;
    }
  }

  // Busca por aproximação
  for (const [chave, modelos] of Object.entries(MODELOS_INDIVIDUAIS_POR_MARCA)) {
    if (
      chave.toLowerCase().includes(marcaNormalizada) ||
      marcaNormalizada.includes(chave.toLowerCase())
    ) {
      return modelos;
    }
  }

  return [];
}
